### ISSUE TITLE
Dead links for .NET 4.6 and Get .NET

### ISSUE THREAD

**Issue by RickStrahl** [shanselman/SmallestDotNet#60]
Using Chrome, with .NET 4.6 installed when I navigate to site it correctly identifies .NET 4.6.

However, the **Get .NET** link does nothing (points href="#" which does nothing - presumably because I'm already on the latest). It'd be nice if this still points to the download location which is what I'd expect here. Or if that's not the intent, remove or disable the button if you assume that the user is already on the latest.

Looks like the download link that was broken earlier has already been fixed.

Scott - really appreciate this site and I link to it from several products. It's kind of sad that there has to be third party site to provide this though... 

Is there any chance that you can get the content management people that deal with this these downloads to have some sort of summary page that doesn't change and shows the latest available versions of the major runtime versions instead of the ever-changing links that not even your specialized site seems to be able to track reliably? It should list 2.0, 3.0, 3.5,4.0, 4.5.x and 4.6 and whatever comes after in descending order, along with a short blurp about what platforms it can run on.

This is something that should be handled by the folks that manage the new versions on the MS site.

**Comment by shanselman** [comment]
Thanks, sorry, it's on my list but it's tedious and while I have a lot of issues I have few PRs.

**Comment by shanselman** [comment]
Oh, and BTW we ARE working on a more official way to do this. @bethmassi

**Comment by BethMassi** [comment]
@RickStrahl dude, shouldn't you be wind surfing right now? Can we rewrite this in FoxPro? ;-) Seriously, yes, we are working on getting the sites in order. Hope all else is well.

**Comment by atifaziz** [comment]
> I have a lot of issues I have few PRs.

@shanselman 40 issues (27 closed) and 29 PRs (27 closed) to date. 73% doesn't look like a bad ratio. :no_mouth: 

> Oh, and BTW we ARE working on a more official way to do this. 

@shanselman As an official replacement for SmallestDotNet? Because it sounds like “Don't waste your time here.”

>  It's kind of sad that there has to be third party site to provide this though...

@RickStrahl Perhaps the “content management people” ought to be contributing PRs here. Perhaps the [links & versions database shouldn't be hard-coded](https://github.com/shanselman/SmallestDotNet/blob/9128cb4f870559b6d5859eba24e84cb8622bc1bc/SmallestDotNetLib/Constants.cs#L33-L80) here and ought to be maintained as a simple text file on GitHub that this app then uses.

**Comment by shanselman** [comment]
@atifaziz What I'm saying is that folks find this useful and that we should make it official and nice and not the mess it is today. I wrote this in an hour years ago and now it gets like 60k views a week. You've correctly pointed out the code is crap, and it is.

PRs appreciated.

**Comment by RickStrahl** [comment]
I for one **really** appreciate that this site is here. I point all of my applications that require runtimes at it for people to figure out what they need to download. It's great. And again it's sad that this has to come from a hobby project like this and not from Microsoft.

The big issue isn't code quality or features IMHO. What's important is that the links work :-) and frankly that's a job for somebody at Microsoft because us on the outside we often don't know what the right links are (those that hopefully are  a little more permanent).

Heck if somebody @ Microsoft content division could manage a feed of version number, type and download link that would be ideal and probably very easy to manage.

**Comment by atifaziz** [comment]
@shanselman Just to be clear, I didn't mean to call-out that the code is crap. The code quality isn't the issue (as @RickStrahl also said) because the true value of what you did in an hour is that it's been helping devs & ops for years, and most importantly, in a very straightforward way!

@RickStrahl You mean something like [“.NET Framework” downloads](https://www.microsoft.com/en-us/download/search.aspx?q=.net%20framework&p=0&r=10&t=&s=Relevancy~Descending) but *simpler*, *stable* and *curated*?

**Comment by atifaziz** [comment]
> PRs appreciated.

@shanselman Here you… #71 :wink:

**Comment by zacglenn** [comment]
@shanselman is this issue resolved? If so, may we have it closed?
